// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentGrid.Api.Data;

#nullable disable

namespace RentGrid.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260419172259_AddUserIsActive")]
    partial class AddUserIsActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentGrid.Api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RentGrid.Api.Models.BookingExtra", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("ExtraServiceId")
                        .HasColumnType("int");

                    b.HasKey("BookingId", "ExtraServiceId");

                    b.HasIndex("ExtraServiceId");

                    b.ToTable("BookingExtras");
                });

            modelBuilder.Entity("RentGrid.Api.Models.ExtraService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ExtraServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "GPS",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Gyerekülés",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Extra biztosítás",
                            Price = 5000m
                        });
                });

            modelBuilder.Entity("RentGrid.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@rentgrid.local",
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "$2a$12$OMuczbfgm9D4Ix.5EhxeKeDmqYFbW464rY2k9TT2yHoYeMiy8K/ja",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("RentGrid.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DailyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MongoImageIds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            DailyPrice = 17500m,
                            IsAvailable = true,
                            Model = "Corolla",
                            MongoImageIds = ""
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Ford",
                            DailyPrice = 16500m,
                            IsAvailable = true,
                            Model = "Focus",
                            MongoImageIds = ""
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BMW",
                            DailyPrice = 32000m,
                            IsAvailable = true,
                            Model = "320i",
                            MongoImageIds = ""
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Škoda",
                            DailyPrice = 18500m,
                            IsAvailable = true,
                            Model = "Octavia",
                            MongoImageIds = ""
                        });
                });

            modelBuilder.Entity("RentGrid.Api.Models.Booking", b =>
                {
                    b.HasOne("RentGrid.Api.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentGrid.Api.Models.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RentGrid.Api.Models.BookingExtra", b =>
                {
                    b.HasOne("RentGrid.Api.Models.Booking", "Booking")
                        .WithMany("BookingExtras")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentGrid.Api.Models.ExtraService", "ExtraService")
                        .WithMany("BookingExtras")
                        .HasForeignKey("ExtraServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ExtraService");
                });

            modelBuilder.Entity("RentGrid.Api.Models.Booking", b =>
                {
                    b.Navigation("BookingExtras");
                });

            modelBuilder.Entity("RentGrid.Api.Models.ExtraService", b =>
                {
                    b.Navigation("BookingExtras");
                });

            modelBuilder.Entity("RentGrid.Api.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("RentGrid.Api.Models.Vehicle", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
